### ISSUE TITLE
v0.3 roadmap

### ISSUE THREAD

**Issue by azuline** [azuline/rose#1]
this ticket covers the items from init -> 0.3, as creating separate issues is kind of silly for the initial bootstrap

browser:

- [x] tag reading
- [x] initial cache population command
- [x] read ops virtual fs
- [x] preliminary README
- [x] cover.{jpg,png} support
- [x] json dump for jq querying
- [x] artist/genre/label hiding (from vfs)
- [x] collages
- [x] writes
- [x] watchdog
- [x] new albums toggling
- [x] added_at sorted view
- [x] subartists / artist aliases
- [x] persistent track IDs
- [x] playlists
  - [x] add to playlist via filesystem...
  - [x] playlist cover art
- [x] support arbitrarily nested release directories (replace scandir w/ walk)
- [x] collage/playlist description_meta autoupdating
- [x] docs dir (unbundle readme; too unorganized)
- [x] trigger cache update after `release` call in virtual fs
- [x] add/modify/delete cover art via virtual fs. accept writes to known valid cover art filenames and ghost file rename

metadata mgmt:

- [x] tag writing
- [x] album file editing as text file
- [x] add validation to album file editing for release type artist roles
- [x] click autocomplete
- [x] rules engine
  - [x] single-matcher rule execution (char normalization / artist,label,genre rename / tag splitting) / stored file
  - [x] act on other tag (e.g. artist:beethoven role=composer)
  - [x] multiple actions
  - [x] dsl for shell + cli editing
  - [x] clean up UI
  - [x] optimize - sqlite fts5
  - [x] cli
  - [x] dry-run flag
  - [x] doc
  - [x] add (for multi-value tags, add a value, like a genre)
- [x] single extractor (extract a song as a single; adjust album-level tags+releasetype)

cleanup:

- [x] virtualfs tests
- [x] replace migrations system with db nuke on mig hash change
- [x] factor artist parsing/formatting semantics into its own package
- [x] no discno in single tag files
- [x] bug: preview-tui syscalls missing
- [x] add more data to stat - mtimes!
- [x] flatten dirs / move testdatas into `$root/testdata/{cache,tagger}`
- [x] move to per-release `.rose.toml` that contains uuid+new; then use `discno/trackno` for playlists
- [x] optimize FUSE (it's 100x slower rn than native, wtf??)
- [x] cache refresh optimization time: possibly mtime tracking w/ `--force` override
- [x] write logs to ~/.local/smthn/rose
- [x] emit log lines for each release deleted b/c no longer on disk (RETURNING supported by sqlite?) 
- [x] error.py -> base_error.py
- [x] bug: unnecessary cache miss for Fading Up collage?
- [x] push sanitize into cache module and handle it all there; return (raw, sanitized) dataclasses
- [x] optimize cold start cache by batching disk writes after the loop
- [x] parallelize cache updates
- [x] config parsing error handling with good messages
- [x] bug: where artists/genre/labels deleted from tags are not evicted from cache
- [x] bug: multiprocessing error propagation from subproces
- [x] invalidate cache on config change
- [x] optimize watcher test
- [x] improve type of artist aliases; it turns out toml has dicts..
- [x] refactor fuse_hide_x configs to a combo of `fuse_x_{white,black}list`
- [x] sqlite locks w/ timeouts for concurrency primitive? i hate worrying about concurrent execution
- [x] collage/playlist update concurrency safety
- [x] toggle new concurrency safety
- [x] move supported ext and rlstypes to tagger. move supported roles to artiststr.
- [x] optimize playlist addition via virtualfs (i didnt realize there would be so many calls to write, we are reallocing way too many times)
- [x] bug: renaming rls/track while track is in a playlist results in track disappearing from playlist until forced cache update
- [x] feature: cover art filenames as config array
- [x] improvement: config value for ignore_directories
- [x] bug: release editor sorts tracks incorrectly: "10" sorts before "2"
- [x] bug: virtual filenames are not unique during playlist editing: the remapping can change IDs if two tracks have the same virtual filename. add temporary collision ids 
- [x] bug: rename playlist art when renaming a playlist
- [x] feature: support parsing release virtual dirname out of path type for CLI args
- [x] bug: audit collage/playlist mechanics when releases are deleted/replaced during update (e.g. during dir rename)
- [x] improvement: before editing any metadata or something, do a mtime check, and a cache update if the mtimes dont match. so that rose doesnt cause a lost write.
- [x] perf: optimize the hell out whatever's making ls slow
- [x] refactor: switch to https://github.com/libfuse/pyfuse3; fusepy is 5 years w/out update. UPDATE: we went with llfuse instead.
- [x] `rose cache unwatch` and pid/de-duplicate detection
- [x] improvement: log rotation
- [x] bug: standard tools error in the vfs "add to playlist/collage" operation. update vfs to pretend to be normal in these situations within a time window (e.g. allow file writing when file writing actually shouldnt be allowed)
- [x] bug: an invalid rename operation can permalock parent directory. might be a fusepy bug; reevaluate after switch to pyfuse3
- [x] bug: collage vfs adder doesnt work if directories are copied from another collage or recently added, because virtual dirname has prefixes. soln: strip a few prefix regexes when attempting to look up...
- [x] compat: mac support (should only require supporting alts. for XDG_*)
- [x] do not hard delete missing music from collage/playlist; instead, add `missing` field
- [x] renaming {NEW} via virtual fs crashes in the cache update... writes the file, cache fails to refresh dirname, vfs fails
- [x] improvement: write rose_release_ids to audio tags too in order to make watchdog updates more robust and prevent double .rose.{uuid}.toml writes
- [x] process: branching strategy: have `release` be the stable branch; master be the unstable branch? update `release` to the latest release version
- [x] optimization: optimize cache again...
- [x] robustness: if release ID in tags, don't process unless force passed, emit explicit warnings
- [x] bug: release cache doesnt invalidate if a track is deleted from a release
- [x] don't schedule duplicate playlist updates (returnval propagate)

docs:

- [x] ingestion: tag splitting behavior
- [x] blacklist/whitelist use case in virtual filesystem
- [x] single extraction

**Comment by azuline** [comment]
playlist id: discno-trackno-collision (collisions organized by title sorted lexographically)
each entry has artist_meta/title_meta/duration_meta/etc - use to match ID if ID not found; otherwise, emit warning
